systemctl stop reflector.service;
timedatectl set-ntp true;
vim /etc/pacman.d/mirrorlist
mkfs.ext4  /dev/sda3;
mkfs.ext4  /dev/sdb1;
mkfs.vfat -F32 /dev/sda2;
mkswap -f /dev/sda2;
swapon /dev/sda2;
mount /dev/sda3  /mnt;
mkdir /mnt/home;
mount /dev/sdb1 /mnt/home;
mkdir /mnt/boot;
mount /dev/sda1 /mnt/boot;
pacstrap /mnt base base-devel linux linux-firmware dhcpcd iwd vim sudo bash-completion;
genfstab -U /mnt > /mnt/etc/fstab;
arch-chroot /mnt;
ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime;
hwclock --systohc;
vim /etc/locale.gen;
locale-gen;
echo 'LANG=en_US.UTF-8'  > /etc/locale.conf;
passwd root;
pacman -S intel-ucode;
pacman -S grub efibootmgr;
grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB;
grub-mkconfig -o /boot/grub/grub.cfg;
exit;
umount -R  /mnt;
reboot;
